### ISSUE TITLE
Export/Import Keyboards

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationKeyboard#19]
Provide a means to export keyboard files via the Android sharing menu.  Include an option to import keyboards.

**Comment by bknatterud** [comment]
are there are features like this and comments that we can put into another milestone release and scope out spec for?

**Comment by bknatterud** [comment]
Export/Import

Support the following

- Bluetooth
- WiFi
- Files Sideloaded on SD Card

**Comment by PeeJWeeJ** [comment]
Feature is included in the most recent beta.
