### ISSUE TITLE
Nexus 5.0.4

### ISSUE THREAD

**Issue by markellishancock** [unfoldingWord-dev/translationKeyboard#23]
tK has been crashing whenever using it in tS or anything else that required text.  I set the input language and minimized the choices down to en.  Still failed.  Uninstalled tK and reinstalled.  I received the same result.  I have sent 2 reports to google's reporting service.  I am installing 5.1 for android because my identical Nexus works well with tK.

**Comment by markellishancock** [comment]
Upgraded Android to 5.1.1 with the same result.  I will set the tablet to factory default.

**Comment by bknatterud** [comment]
One issue that is making this more difficult is that in the stacktrace it is giving a message of unknown source further down in the stacktrace. We are trying to track down the issue but just an FYI that that is making it more difficult.

**Comment by markellishancock** [comment]
Do you need a tablet that is doing the same thing?

**Comment by markellishancock** [comment]
I gave the person involved a Samsung 7" tablet and unfortunately the same thing happened with tK.

**Comment by bknatterud** [comment]
If we can't reproduce it on our end we may need to locate the same tablet. I should know tomorrow sometime if we are able to reproduce the issue.

**Comment by bknatterud** [comment]
Just posted a .apk in the translationKeyboard channel on Slack that should fix this issue.

**Comment by bknatterud** [comment]
I believe this issue has been resolved.
