### ISSUE TITLE
Keyboard Won't Launch

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationKeyboard#27]
When some layouts are selected the keyboard will not launch, the ones I've identified are:

* Devangari (ne_NP)
* Android 4 row (th_00)

**Comment by bknatterud** [comment]
by not launch to you mean that the keyboard never comes up when you tap in an area for your cursor to be?

**Comment by jag3773** [comment]
Correct.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by bknatterud** [comment]
ok, can you uninstall tK and try again? I'm not seeing the issue on our Android's here and Mark Hancock says it is working for him. Sorry.

**Comment by jag3773** [comment]
Fresh install did fix it.  What does that mean for existing installs updating the app?

**Comment by bknatterud** [comment]
Yes, we are testing to make sure that upgrades from the Play Store will upgrade properly. We have that working with our current build internally now.
