### ISSUE TITLE
app dies when going to "keyboard sharing"

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationKeyboard#28]
for 2.1.0-5 beta

**Comment by bknatterud** [comment]
build 61 posted in the translationkeyboard channel in slack should fix that issue. Please confirm.

**Comment by bknatterud** [comment]
now just posted build 62 here which should also be good and is the latest. 
https://github.com/unfoldingWord-dev/translationKeyboard/releases/tag/2.1.0-beta2
