### ISSUE TITLE
tK Wants to Manage apks

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/translationKeyboard#45]
After installing latest build and then trying to install another apk I'm asked if I want the package installer or tK to open the file.  Seems like a bug, but maybe a side effect of importing tk file?

**Comment by PeeJWeeJ** [comment]
I just noticed this in the uW work as well. I'm looking into it and should have a fix for it today.

**Comment by bknatterud** [comment]
Fixed is available in this release...
https://github.com/unfoldingWord-dev/translationKeyboard/releases/tag/2.1.0-beta5
