### ISSUE TITLE
App cannot be installed on toshiba 8"

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/translationKeyboard#47]
Device
---
Toshiba 8"
release: https://github.com/unfoldingWord-dev/translationKeyboard/releases/tag/2.1.0-beta5
Android 4.4.2
model: AT7-C

Description
---

`This app isn't compatible with your tablet`

We had a similar issue with ts-android which ended up being a result of using the `apache.commons` library. See this commit https://github.com/unfoldingWord-dev/ts-android/commit/d50b6c6622f6e8de4ad817773de496c07579457b.

In order to fix this I had to manually download the .jar file and include it in the libs dir:

![screenshot_082515_111519_am](https://cloud.githubusercontent.com/assets/166412/9475280/931c5d24-4b1a-11e5-86ed-fb3d3b94789a.jpg)

You can download the library here: https://commons.apache.org/proper/commons-io/download_io.cgi

Not saying this is the issue, but if it is that's all the info you should need to fix it.

**Comment by bknatterud** [comment]
we are hoping release https://github.com/unfoldingWord-dev/translationKeyboard/releases/tag/2.1.0-beta6 fixes this issue.

Let me know.

**Comment by PeeJWeeJ** [comment]
Should be fixed now, re-open if it's still an issue.
