### ISSUE TITLE
enter button on en kb inputs "Go" in browser in...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/translationKeyboard#52]
Notes
======
enter button on en kb inputs "Go" in browser instead of triggering go. acz kb works correctly.

Environment
======
Environment Key | Value
:----: | :----:
version | 2.0.0
build | 83
UDID | b9dab5f75e6c9732
Android Release | 4.4.2
Android SDK | 19
Brand | Dragon_Touch
Device | E97

**Comment by PeeJWeeJ** [comment]
Fixed in beta8
